M48
; DRILL file {KiCad (6.0.9)} date Sat Dec 24 03:55:55 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-24T03:55:55+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.4028Y-2.9911
X4.4028Y-3.1821
T2
X4.2835Y-2.9793
X4.2835Y-3.1939
T0
M30
